version: "3.4"
services:
  web:
    env_file: .env
    build:
      context: .
      target: build
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
volumes:
  node_modules:
